version: "3.8"

services:
  geth:
    image: ethereum/client-go:v1.13.5
    ports:
      - "8545:8545"
      - "8546:8546"
    command:
      - --miner.gaslimit=12000000
      - --http
      - --http.api=personal,eth,net,web3,debug
      - --http.vhosts=*
      - --http.addr=0.0.0.0
      - --ws
      - --ws.api=personal,eth,net,web3,debug
      - --ws.addr=0.0.0.0
      - --allow-insecure-unlock
      - --rpc.allow-unprotected-txs
      - --dev
      - --verbosity=2
      - --nodiscover
      - --maxpeers=0
      - --mine
      - --networkid=1337

  rundler:
    image: truewallet/rundler:latest
    depends_on:
      - geth
    ports:
      - "8080:8080"
      - "3000:3000"
    environment:
      - ENTRY_POINTS=0x5FF137D4b0FDCD49DcA30c7CF57E578a026d2789
      - NODE_HTTP=http://geth:8545
      # 0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266
      - BUILDER_PRIVATE_KEY=0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80
      - CHAIN_ID=1337
    healthcheck:
      test: curl --fail http://localhost:3000/health || exit 1
      interval: 1s
      timeout: 1s
      retries: 60
      start_period: 10s
